// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_Ka2gm7wfv2egRh72SniA6n3YYwsCI4',
    appId: '1:851444923512:web:bb95cfa679f1c52fe8c18d',
    messagingSenderId: '851444923512',
    projectId: 'mazabeton-final-a6b1f',
    authDomain: 'mazabeton-final-a6b1f.firebaseapp.com',
    storageBucket: 'mazabeton-final-a6b1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsxjUqOc-hWRuREomvWLWIy6GT_D_5c0',
    appId: '1:851444923512:android:431e4b2dafc77b44e8c18d',
    messagingSenderId: '851444923512',
    projectId: 'mazabeton-final-a6b1f',
    storageBucket: 'mazabeton-final-a6b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEFvV6j33JyO2sr1N_pMPSOqVQd31ZLJo',
    appId: '1:851444923512:ios:e011371af9ddc9ffe8c18d',
    messagingSenderId: '851444923512',
    projectId: 'mazabeton-final-a6b1f',
    storageBucket: 'mazabeton-final-a6b1f.firebasestorage.app',
    iosBundleId: 'com.example.mazabeton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEFvV6j33JyO2sr1N_pMPSOqVQd31ZLJo',
    appId: '1:851444923512:ios:e011371af9ddc9ffe8c18d',
    messagingSenderId: '851444923512',
    projectId: 'mazabeton-final-a6b1f',
    storageBucket: 'mazabeton-final-a6b1f.firebasestorage.app',
    iosBundleId: 'com.example.mazabeton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6_Ka2gm7wfv2egRh72SniA6n3YYwsCI4',
    appId: '1:851444923512:web:afaac9e69003431ce8c18d',
    messagingSenderId: '851444923512',
    projectId: 'mazabeton-final-a6b1f',
    authDomain: 'mazabeton-final-a6b1f.firebaseapp.com',
    storageBucket: 'mazabeton-final-a6b1f.firebasestorage.app',
  );
}
