// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDm3VZLC9l9M6AmqCGBkUOucYiUQBVt8',
    appId: '1:969191232674:web:2cb5ff52666c52f4e4b3fb',
    messagingSenderId: '969191232674',
    projectId: 'mazabeton-2fefb',
    authDomain: 'mazabeton-2fefb.firebaseapp.com',
    storageBucket: 'mazabeton-2fefb.firebasestorage.app',
    measurementId: 'G-K4YNP6ZWV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAKBReAqpkmrsnEyVbEl4jYRz9gyR9U8',
    appId: '1:969191232674:android:492be723243ef20be4b3fb',
    messagingSenderId: '969191232674',
    projectId: 'mazabeton-2fefb',
    storageBucket: 'mazabeton-2fefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAliPR1QLab8XZmrzhNSUJ7-kEBc8JtxfU',
    appId: '1:969191232674:ios:923c26e3e6e72367e4b3fb',
    messagingSenderId: '969191232674',
    projectId: 'mazabeton-2fefb',
    storageBucket: 'mazabeton-2fefb.firebasestorage.app',
    iosBundleId: 'com.example.mazabeton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAliPR1QLab8XZmrzhNSUJ7-kEBc8JtxfU',
    appId: '1:969191232674:ios:923c26e3e6e72367e4b3fb',
    messagingSenderId: '969191232674',
    projectId: 'mazabeton-2fefb',
    storageBucket: 'mazabeton-2fefb.firebasestorage.app',
    iosBundleId: 'com.example.mazabeton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzDm3VZLC9l9M6AmqCGBkUOucYiUQBVt8',
    appId: '1:969191232674:web:13438e0391fa6004e4b3fb',
    messagingSenderId: '969191232674',
    projectId: 'mazabeton-2fefb',
    authDomain: 'mazabeton-2fefb.firebaseapp.com',
    storageBucket: 'mazabeton-2fefb.firebasestorage.app',
    measurementId: 'G-BCCRW75VN6',
  );
}
